"""add reading words table

Revision ID: 53c81d00053c
Revises: 0001_initial
Create Date: 2026-08-04 20:38:56.929924

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa




# revision identifiers, used by Alembic.
revision: str = '53c81d00053c'
down_revision: Union[str, Sequence[str], None] = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
